version: "3.7"
services:
  postgres:
    image: postgres:11.3
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=calorieDB
    volumes:
      - "/var/docker_volumes/calorieDB:/var/lib/postgresql/data"
    restart: always
    ports:
      - 5432:5432
volumes:
  postgres:
